Prune with glorot uniform normalization
dorimedini/kardashigans pull request #105
Opened 2019-08-22 20:03 UTC by dorimedini

Addresses #104 , rebased on top of #102

Got new results, still can't see correlation though... winnery intersection and robustness don't follow the same pattern

![image](https://user-images.githubusercontent.com/3027929/63545745-ca9e8800-c530-11e9-8c03-5a776edf0f39.png)
![image](https://user-images.githubusercontent.com/3027929/63545749-ce320f00-c530-11e9-905b-61e42d05fc0a.png)
![image](https://user-images.githubusercontent.com/3027929/63545761-d12cff80-c530-11e9-83aa-3759e3f7434f.png)
![image](https://user-images.githubusercontent.com/3027929/63545765-d38f5980-c530-11e9-9201-823790266c1c.png)

2019-08-23 12:51 UTC, galshachaf requested changes

2019-08-23 12:51 UTC, galshachaf commented on trainer.py
> +        ret = (not self._regularizer) or self._regularizer == 'glorot_uniform'
regularizer or initializer?

2019-08-23 14:52 UTC, dorimedini commented on trainer.py
> +        ret = (not self._regularizer) or self._regularizer == 'glorot_uniform'
Fixed (commit 84da80a)

2019-08-24 10:17 UTC, galshachaf approved these changes

2019-08-24 11:37 UTC, merged